# Generated by Django 5.1.1 on 2025-04-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('effect', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.IntegerField(default=1)),
                ('school_points', models.IntegerField(default=0)),
                ('has_primary_school', models.BooleanField(default=False)),
                ('has_high_school', models.BooleanField(default=False)),
                ('has_university', models.BooleanField(default=False)),
                ('in_primary_school', models.BooleanField(default=False)),
                ('in_high_school', models.BooleanField(default=False)),
                ('in_university', models.BooleanField(default=False)),
                ('has_white_cane', models.BooleanField(default=False)),
                ('has_guide_dog', models.BooleanField(default=False)),
                ('has_instrument', models.BooleanField(default=False)),
                ('knows_music', models.BooleanField(default=False)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('skip_turn', models.BooleanField(default=False)),
                ('waiting_for_dog', models.BooleanField(default=False)),
                ('waiting_for_job', models.CharField(blank=True, max_length=50, null=True)),
                ('just_crossed_start', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('description', models.TextField()),
                ('effect', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_turn', models.IntegerField(default=0)),
                ('log', models.TextField(blank=True, null=True)),
                ('players', models.ManyToManyField(to='tarsasjatek.player')),
            ],
        ),
    ]
